sudo: false
language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --without docs development

script: bundle exec rake

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: ml+Ph8FuoU4TgEqGmjERaF5peoNTRhllG5rBFDUgGxPCKRxE9snYDwc+29RAhA7izlaUABIA3fWT11SdF2RMTUorsrz0PbYtyBZuI9AKloww1CUFMl2kr8+DRt/AzMcGYs8OgQW12NLNNRV72X4wUKsJXpazVHsXctU/Fh/AqX0=
